config/routes.rb
Rails.application.routes.draw do
  # devise gem authentication routes for users
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # get 'pages/home', to: 'pages#home'
  # get 'pages/about', to: 'pages#about'

  # To make this the default homepage
  root to: "pages#home"

  get "about", to: "pages#about"

  # Gives all the articles routes
  resources :articles

  # users signup routes
  get "signup", to: "users#new"
  # users login and logout routes
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"

  # users routes
  resources :users, except: [:new]

  # categories routes
  resources :categories, expect: [:destroy]
end

app/models/article.rb
class Article < ApplicationRecord
  # one-to-many associations
  belongs_to :user
  # many-to-many associations
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # before_action will execute in the order they were called
  before_action :set_article, only: [:show, :update, :edit, :destroy]

  # Restricting access for some actions based on the login and logout state of a user
  # before_action :require_user, except: [:index, :show]
  # before_action :require_same_user, only: [:edit, :update, :destroy]

  # new and create, edit and update are dependent on each other
  def index
    # @articles = Article.all
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    # It will render the data in an object like form
    # render plain: params[:article].inspect

    @article = Article.new(article_params)
    # Hard-coded user_id for one-to-many-association because it is mandatory
    @article.user = current_user

    respond_to do |format|
      if @article.save
        flash[:success] = "Article was successfully created!"
        format.html {
          redirect_to article_path(@article)
        }
        format.js
      else
        # NOTE: this will render `new.erb` and set
        #       `Content-Type: text/html` header;
        #       turbo is happy.
        format.html {
          render(:new, status: :unprocessable_entity)
        }
        render "new"
      end
    end
  end

  def edit
    # @article = Article.find(params[:id])
  end

  def update
    # @article = Article.find(params[:id])
    respond_to do |format|
      if @article.update(article_params)
        flash[:success] = "Article was successfully updated!"
        format.html {
          redirect_to article_path(@article)
        }
        format.js
      else
        format.html {
          render(:edit, status: :unprocessable_entity)
        }
        render "new"
      end
    end
  end

  def show
    # @article = Article.find(params[:id])
  end

  def destroy
    # @article = Article.find(params[:id])
    @article.destroy
    flash[:danger] = "Article was successfully deleted!"
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def set_article
    @article = Article.find(params[:id])
  end

  # def require_same_user
  #   if current_user != @article.user && !current_user.admin?
  #     flash[:danger] = "You can only edit or delete your own articles!"
  #     redirect_to root_path
  #   end
  # end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article)%>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
            <small>
              Created by: <%= article.user.username if article.user %>,
              <%= time_ago_in_words(article.created_at) %> ago,
              Last Updated: <%= time_ago_in_words(article.updated_at) %> ago
            </small>
          </div>
        </div>
        <%# Categories %>
        <% if article.categories.any? %>
          <p>Categories: <%= render article.categories %></p>
        <% end %>
        <%# if logged_in? && (current_user == article.user || current_user.admin?) %>
        <% if user_signed_in? && (current_user == article.user || current_user.admin?) %>
          <div class="article-actions">
            <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete this article", article_path(article),
              data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'},
              class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_edit_modal.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content", style="height: 49rem;margin-top: 5.2rem;">
    <div class="modal-header">
      <h3 align="center", class="modal-title" id="edit-modal-<%= @article %>"><b>Edit an Article</b></h3>
      <%# <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button> %>
    </div>
    <div class="modal-body",>
      <%= form_with(model: @article, local: false, turbo: false) do |f| %>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :title %>
          </div>
          <div class="col-sm-10" >
            <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true, style:"margin-bottom: 15px;" %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2"
>
            <%= f.label :description %>
          </div>
          <div class="col-sm-10">
            <%= f.text_area :description, rows: 10, class: "form-control",style:"margin-bottom: 15px;resize:none;height:20rem",placeholder: "Body of article" %>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-sm-offset-2 col-md-9">
              <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class:"checkbox") + cb.text} %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div align="center", class="col-sm-offset-1 col-sm-2">
            <%= f.submit "Update Article", class: "btn btn-warning btn-lg", id:"update" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-4 col-sm-4">
            <%= link_to "Cancel Request", articles_path, class: "btn btn-warning btn-lg", id:"update" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<%# To remove redundancy, this file has been created. %>
<%= render 'shared/errors', obj: @article%>
<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class:"checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/_modal.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h3 align="center", class="modal-title" id="exampleModalLabel"><b>Create an Article</b>
      </h3>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class='row'>
        <div class='col-md-20'>
          <%= form_with(model: Article.new, local: false, turbo: false) do |f| %>
            <div class="form-group">
              <div class="control-label col-sm-2">
                <%= f.label :title %>
              </div>
              <div class="col-sm-10" >
                <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true, style:"margin-bottom: 15px;" %>
              </div>
            </div>
            <div class="form-group">
              <div class="control-label col-sm-2"
>
                <%= f.label :description %>
              </div>
              <div class="col-sm-10">
                <%= f.text_area :description, rows: 10, class: "form-control",style:"margin-bottom: 15px",placeholder: "Body of article" %>
              </div>
            </div>
            <div class="form-group">
              <div class="row">
                <div class="col-sm-offset-2 col-md-9">
                  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                    <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class:"checkbox") + cb.text} %>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div align="center", class="col-sm-offset-1 col-sm-10">
                <%= f.submit class: 'btn btn-success btn-lg' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/articles/create.js.erb
$('#articles').prepend("<%= j render @article %>");
$('#exampleModal').modal('hide');
$('#exampleModal').on('hidden.bs.modal', function (event) {
$(this).find('input[type="text"], textarea').val('');
});

app/views/articles/edit.html.erb
<%# <h1 align ="center"> Edit existing article </h1> %>
<div class="background">
<div class="blur"></div>
</div>
<div class="modal show fade in" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
  <%= render 'edit_modal', local: {article: @article} %>
</div>
<%#= render 'form' %>

app/views/articles/edit.js.erb
$('#editModal').modal('open');
$('#editModal').on('open.bs.modal', function (event) {
$(this).find('input[type="text"], textarea').val('');
});

app/views/articles/index.html.erb
<h1 align="center"> Listing all Articles</h1>
<div align="center">
  <%= will_paginate %>
</div>
<div>
  <%#= link_to ' New Article', class:"btn btn-primary", data_toggle: "modal", data_target: "#exampleModal" %>
</div>
<%if user_signed_in?%>
  <h3 align="center">
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModal" >
      New Article
    </button>
  </h3>
  <div class="modal fade in", id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <%= render 'modal' %>
  </div>
<%end%>
<div id="articles">
  <%= render 'article', obj: @articles %>
</div>
<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center"> Create an Article </h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <% if @article.user %>
    <ul class="listing">
      <div class="row center">
        <div class="col-md-4 col-md-offset-4">
          <li>Create by:</li>
          <li>
            <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
          </li>
          <li class=""article-title>
            <%= link_to @article.user.username, user_path(@article.user)%>
          </li>
          <li>
            <small>
              <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
            </small>
          </li>
        </div>
      </div>
    </ul>
  <% end %>
  <h4 class="center description">
    <strong>
      Description:
    </strong>
  </h4>
  <hr>
  <%= simple_format(@article.description) %>
  <% if @article.categories.any? %>
    <%# will have the same effect as @article.categories.each do ... %>
    <p>Categories: <%= render @article.categories %></p>
  <% end %>
  <div class="article-actions">
    <%# if logged_in? && (current_user == @article.user || current_user.admin?)%>
    <% if user_signed_in? && (current_user == @article.user || current_user.admin?)%>
      <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete this article", article_path(@article),
        data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'},
        class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/articles/update.js.erb
document.getElementById("update").addEventListener("click", function() {
// Create a new XMLHttpRequest object
var xhttp = new XMLHttpRequest();
// Define the callback function
xhttp.onreadystatechange = function() {
if (this.readyState == 4 && this.status == 200) {
// Update the content with the response from the server
document.getElementById("content").innerHTML = this.responseText;
}
};
// Open the request and send it to the server
xhttp.open("GET", "update.js", true);
xhttp.send();
});