config/routes.rb
Rails.application.routes.draw do
  # devise gem authentication routes for users
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # get 'pages/home', to: 'pages#home'
  # get 'pages/about', to: 'pages#about'

  # To make this the default homepage
  root to: "pages#home"

  get "about", to: "pages#about"

  # Gives all the articles routes
  resources :articles

  # users signup routes
  get "signup", to: "users#new"
  # users login and logout routes
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"

  # users routes
  resources :users, except: [:new]

  # categories routes
  resources :categories, expect: [:destroy]
end

app/views/layouts/_footer.html.erb
<div class="container", style="position: relative;bottom:0">
  <footer class="footer">
    <small>
      Copyright &copy; <a href="#">Harsh Sharma</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}"%>'>
        <a href="#" class="close" data-dismiss="alert"> &#215;</a>
        <%=content_tag :div, msg, :id=>"flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>
 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <%# if logged_in? %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li>
                <li> <%= link_to "New Article", new_article_path %></li>
              </li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <li> <%= link_to "All Categories", categories_path %></li>
            </li>
            <% Category.all.each do |category| %>
              <li><%= link_to "#{category.name}", category_path(category) %></li>
            <% end %>
            <% if user_signed_in? and current_user.admin? %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Create New Category", new_category_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <%# if logged_in? %>
        <% if user_signed_in? %>
          <li>
            <%#= button_to 'Logout', logout_path, method: :delete, class:'logout-btn' %>
            <%= button_to 'Logout', destroy_user_session_path, method: :delete, class:'logout-btn' %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile
              <%= "Admin" if current_user.admin? %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li>
                <%#= link_to "Edit your profile", edit_user_path(current_user) %>
                <%= link_to "Edit your profile", edit_user_registration_path(current_user) %>
              </li>
              <li><%= link_to "View your profile", user_path(current_user)%></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
          <li>
            <%#= link_to 'Log in', login_path %>
            <%= link_to 'Log in', new_user_session_path %>
          </li>
          <li>
            <%#=link_to 'Sign up', signup_path %>
            <%= link_to 'Sign up', new_user_registration_path %>
            <li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    <%# Adds information about controller, action, id, etc %>
    <%# Jquery Scripts %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>